[package]
name = "distrand"
version = "0.1.0"
authors = ["Sam Wilson <tecywiz121@hotmail.com>"]

[dependencies]
bincode = "1.0.1"
crypto-mac = "0.7.0"
rand = "0.5.5"
serde = "1.0.70"
typenum = "1.0"
error-chain = "0.12.0"

[dev-dependencies]
hmac = "0.7.0"
sha2 = "0.8.0"
